### ISSUE TITLE
Unable to import realm

### ISSUE THREAD

**Issue by elpmid** [dasniko/testcontainers-keycloak#1]
Hi,

I was wondering if you are having troubles importing a previously exported realm?

I use the withRealmImportFile("elpmid-realm.json"); method and get the following warning and the realm is not imported.

KC-SERVICES0005: Unable to import realm elpmid from file /tmp/superloop-realm.json.: java.lang.RuntimeException: Script upload is disabled.

To fix the problem I had to add the following to the Class.Method: KeycloakContainer.configure()

withCommand("-Dkeycloak.profile.feature.upload_scripts=enabled");

Does this work for you?

PS - nice library you have written!

thanks

**Comment by elpmid** [comment]
Seems to be due to the complexity of the json file. Your test-realm.json file  works fine, but a fully exported realm gives the stated warning and does not import the realm.

**Comment by dasniko** [comment]
Hi,
I'm happy to hear that you like my app.

Script uploads have been disabled with Keycloak 8.x starting, due to security reasons. Please see mailinglist or release notes for details.

If you have a realm where you need to import scripts, the setting you've used is correct.

Would you expect a method like `.withScriptUploadEnabled()` with the testcontainer?

**Comment by elpmid** [comment]
Hi,

thanks for the quick response. The solution you have proposed would be great.

cheers

**Comment by dasniko** [comment]
This is contained in [release 1.3.0](https://github.com/dasniko/testcontainers-keycloak/releases/tag/1.3.0), which is already pushed to maven central and should be available within the next few hours.
